baseURL = 'https://lanzainc.xyz/'
locale = 'zh-cn'
title = 'lanzainc.xyz'
theme = "PaperMod"

[params]
  defaultTheme = "auto"
  summaryLength = 30
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowRssButtonInSectionTermList = true
  mainSections = ["posts", "gallery", "tech", "playroom"]

[params.profileMode]
  enabled = true
  title = "Lanza Schneider 的小站"
  subtitle = """
  ---
  #### 赛博流浪汉 · 非主流歌手 · 游戏开发者 · 足球迷
  ---
  ##### 下列为联系方式，内容索引可看右上角
  """
  imageUrl = "favicon.png"
  imageTitle = "Ray"
  imageWidth = 128
  imageHeight = 128
  
[[params.profileMode.buttons]]
  name = "博文标签目录"
  url = "tags"
[[params.profileMode.buttons]]
  name = "关于我"
  url = "internal/about"
[[params.socialIcons]]
  name = "github"
  url = "https://github.com/LanzaSchneider"
[[params.socialIcons]]
  name = "discord"
  url = "https://discord.com/users/973357933670846495"
[[params.socialIcons]]
  name = "email"
  url = "mailto:schneiderlanza@gmail.com"

[params.assets]
  favicon = "favicon.png"

[params.cover]
  hidden = false
  hiddenInList = false
  hiddenInSingle = false

[markup.goldmark.renderer]
  unsafe = true

[[menu.main]]
  identifier = "posts"
  name = "博文"
  url = "/posts/"
  weight = 10
[[menu.main]]
  identifier = "gallery"
  name = "画廊"
  url = "/gallery/"
  weight = 20
[[menu.main]]
  identifier = "playroom"
  name = "玩所"
  url = "/playroom/"
  weight = 30
[[menu.main]]
  identifier = "tech"
  name = "科技"
  url = "/tech/"
  weight = 40
